Assignment10 -v4

diff --git a/.github/workflows/packer-ci-build-app.yml b/.github/workflows/packer-ci-build-app.yml
--- a/.github/workflows/packer-ci-build-app.yml
+++ b/.github/workflows/packer-ci-build-app.yml
@@ -65,3 +65,50 @@ jobs:
           ami_id=$(echo "$output" | grep -oP 'ami-\w+')
           echo "AMI_ID=\"$ami_id\"" >> $GITHUB_ENV
 
+      - name: install jq
+        run: |
+          sudo apt-get install jq
+
+      - name: Configure AWS CLI
+        run: |
+          aws configure set aws_access_key_id ${{ secrets.DEMO_ACCESS_KEY_ID }} && \
+          aws configure set aws_secret_access_key ${{ secrets.DEMO_SECRET_ACCESS_KEY }} && \
+          aws configure set region ${{ vars.AWS_REGION }} && \
+          aws configure set default.output_format json
+
+      - name: Create Launch Template Version
+        run: |
+          aws configure set aws_access_key_id ${{ secrets.DEMO_ACCESS_KEY_ID }} && \
+          aws configure set aws_secret_access_key ${{ secrets.DEMO_SECRET_ACCESS_KEY }} && \
+          aws configure set region ${{ vars.AWS_REGION }} && \
+          aws configure set default.output_format json
+          ami_id=$(cat output-ami-id.txt)
+          aws ec2 create-launch-template-version --launch-template-name ${{ vars.LAUNCH_TEMPLATE_NAME }} --source-version '$Latest' --launch-template-data '{"ImageId": "'$ami_id'"}'
+
+      - name: Refresh Auto Scaling Group
+        run: |
+          aws configure set aws_access_key_id ${{ secrets.DEMO_ACCESS_KEY_ID }} && \
+          aws configure set aws_secret_access_key ${{ secrets.DEMO_SECRET_ACCESS_KEY }} && \
+          aws configure set region ${{ vars.AWS_REGION }} && \
+          aws configure set default.output_format json
+          aws autoscaling start-instance-refresh --auto-scaling-group-name ${{ vars.AUTO_SCALING_GROUP_NAME }}
+
+      - name: Wait for Instance Refresh
+        run: |
+            aws configure set aws_access_key_id ${{ secrets.DEMO_ACCESS_KEY_ID }} && \
+            aws configure set aws_secret_access_key ${{ secrets.DEMO_SECRET_ACCESS_KEY }} && \
+            aws configure set region ${{ vars.AWS_REGION }} && \
+            aws configure set default.output_format json
+            completed="false"
+            while [ "$completed" != "true" ]; do
+              status=$(aws autoscaling describe-instance-refreshes --auto-scaling-group-name ${{ vars.ASG_NAME }} --query 'InstanceRefreshes[0].Status' --output text)
+              if [ "$status" == "Successful" ]; then
+                completed="true"
+              elif [ "$status" == "Failed" ]; then
+                echo "Instance refresh failed"
+                exit 1
+              fi
+              sleep 20
+            done
+            
+
