assignment 10 -v5

diff --git a/.github/workflows/packer-ci-build-app.yml b/.github/workflows/packer-ci-build-app.yml
--- a/.github/workflows/packer-ci-build-app.yml
+++ b/.github/workflows/packer-ci-build-app.yml
@@ -53,7 +53,7 @@ jobs:
         run: |
           cd ./packer
           VOLUME_SIZE_INT=$(printf '%d' "$VOLUME_SIZE")
-          output=$(packer build -var "aws_region=${{ env.AWS_REGION }}" \
+          packer build -var "aws_region=${{ env.AWS_REGION }}" \
             -var "demo_account_id=${{ env.DEMO_ACCOUNT_ID }}" \
             -var "instance_type=${{ env.INSTANCE_TYPE }}" \
             -var "source_ami=${{ env.SOURCE_AMI }}" \
@@ -61,9 +61,7 @@ jobs:
             -var "subnet_id=${{ env.SUBNET_ID }}" \
             -var "volume_size=${VOLUME_SIZE_INT}" \
             -var "volume_type=${{ env.VOLUME_TYPE }}" \
-            ami.us-west-2.pkr.hcl)
-          ami_id=$(echo "$output" | grep -oP 'ami-\w+')
-          echo "AMI_ID=\"$ami_id\"" >> $GITHUB_ENV
+            ami.us-west-2.pkr.hcl
 
       - name: install jq
         run: |
@@ -95,20 +93,20 @@ jobs:
 
       - name: Wait for Instance Refresh
         run: |
-            aws configure set aws_access_key_id ${{ secrets.DEMO_ACCESS_KEY_ID }} && \
-            aws configure set aws_secret_access_key ${{ secrets.DEMO_SECRET_ACCESS_KEY }} && \
-            aws configure set region ${{ vars.AWS_REGION }} && \
-            aws configure set default.output_format json
-            completed="false"
-            while [ "$completed" != "true" ]; do
-              status=$(aws autoscaling describe-instance-refreshes --auto-scaling-group-name ${{ vars.ASG_NAME }} --query 'InstanceRefreshes[0].Status' --output text)
-              if [ "$status" == "Successful" ]; then
-                completed="true"
-              elif [ "$status" == "Failed" ]; then
-                echo "Instance refresh failed"
-                exit 1
-              fi
-              sleep 20
-            done
+          aws configure set aws_access_key_id ${{ secrets.DEMO_ACCESS_KEY_ID }} && \
+          aws configure set aws_secret_access_key ${{ secrets.DEMO_SECRET_ACCESS_KEY }} && \
+          aws configure set region ${{ vars.AWS_REGION }} && \
+          aws configure set default.output_format json
+          completed="false"
+          while [ "$completed" != "true" ]; do
+            status=$(aws autoscaling describe-instance-refreshes --auto-scaling-group-name ${{ vars.ASG_NAME }} --query 'InstanceRefreshes[0].Status' --output text)
+            if [ "$status" == "Successful" ]; then
+              completed="true"
+            elif [ "$status" == "Failed" ]; then
+              echo "Instance refresh failed"
+              exit 1
+            fi
+            sleep 20
+          done
             
 
